% This is used to set the path to visible images
%?????????????????????????????????
% Please change the path in line 16 to your own path before running
%?????????????????????16???????????????????????????????????????
% Author:Xingchen Zhang, Ping Ye, Gang Xiao
% Contact: xingchen.zhang@imperial.ac.uk
%
% If you use this code, please site the following paper:
%
% X. Zhang, P. Ye, G. Xiao. VIFB:A Visible and Infrared Benchmark. In
% Proceedings of the IEEE/CVF Conference on Computer Vision and Pattern
% Recognition Workshops, 2020.

function imgs=configImgsIR

    path = 'C:\Users\Administrator\Desktop\20230225VIF\VIFB1\input\roadscene\';

    a = 1
    
    if a == 1
        img_IR = {
            
        %struct('name','A1','path',strcat(path,'Infrared_HUI\'),'ext','jpg'),...
        %struct('name','A2','path',strcat(path,'Infrared_HUI\'),'ext','jpg'),...
        %struct('name','A3','path',strcat(path,'Infrared_HUI\'),'ext','jpg'),...
        %struct('name','A4','path',strcat(path,'Infrared_HUI\'),'ext','jpg'),...
        %struct('name','A5','path',strcat(path,'Infrared_HUI\'),'ext','jpg'),...
        %struct('name','A6','path',strcat(path,'Infrared_HUI\'),'ext','jpg'),...
        %struct('name','A7','path',strcat(path,'Infrared_HUI\'),'ext','jpg'),...
        %struct('name','A8','path',strcat(path,'Infrared_HUI\'),'ext','jpg'),...
        %struct('name','A9','path',strcat(path,'Infrared_HUI\'),'ext','jpg'),...
        %struct('name','A10','path',strcat(path,'Infrared_HUI\'),'ext','jpg'),...
        %struct('name','A11','path',strcat(path,'Infrared_HUI\'),'ext','jpg'),...
        %struct('name','A12','path',strcat(path,'Infrared_HUI\'),'ext','jpg'),...
        %struct('name','A13','path',strcat(path,'Infrared_HUI\'),'ext','jpg'),...
        %struct('name','A14','path',strcat(path,'Infrared_HUI\'),'ext','jpg'),...
        %struct('name','A15','path',strcat(path,'Infrared_HUI\'),'ext','jpg'),...
        %struct('name','A16','path',strcat(path,'Infrared_HUI\'),'ext','jpg'),...
        %struct('name','A17','path',strcat(path,'Infrared_HUI\'),'ext','jpg'),...
        %struct('name','A18','path',strcat(path,'Infrared_HUI\'),'ext','jpg'),...
        %struct('name','A19','path',strcat(path,'Infrared_HUI\'),'ext','jpg'),...
        %struct('name','A20','path',strcat(path,'Infrared_HUI\'),'ext','jpg'),...
        %struct('name','A21','path',strcat(path,'Infrared_HUI\'),'ext','jpg'),...
        %struct('name','A22','path',strcat(path,'Infrared_HUI\'),'ext','jpg'),...
        %struct('name','A23','path',strcat(path,'Infrared_HUI\'),'ext','jpg'),...
        %struct('name','A24','path',strcat(path,'Infrared_HUI\'),'ext','jpg'),...
        %struct('name','A25','path',strcat(path,'Infrared_HUI\'),'ext','jpg'),...
        
        
        %struct('name','1','path',strcat(path,'ir_use_hui\'),'ext','jpg'),...
        %struct('name','2','path',strcat(path,'ir_use_hui\'),'ext','jpg'),...
        %struct('name','3','path',strcat(path,'ir_use_hui\'),'ext','jpg'),...
        %struct('name','4','path',strcat(path,'ir_use_hui\'),'ext','jpg'),...
        %struct('name','5','path',strcat(path,'ir_use_hui\'),'ext','jpg'),...
        %struct('name','6','path',strcat(path,'ir_use_hui\'),'ext','jpg'),...
        %struct('name','7','path',strcat(path,'ir_use_hui\'),'ext','jpg'),...
        %struct('name','8','path',strcat(path,'ir_use_hui\'),'ext','jpg'),...
        %struct('name','9','path',strcat(path,'ir_use_hui\'),'ext','jpg'),...
        %struct('name','10','path',strcat(path,'ir_use_hui\'),'ext','jpg'),...
        %struct('name','11','path',strcat(path,'ir_use_hui\'),'ext','jpg'),...
        %struct('name','12','path',strcat(path,'ir_use_hui\'),'ext','jpg'),...
        %struct('name','13','path',strcat(path,'ir_use_hui\'),'ext','jpg'),...
        %struct('name','14','path',strcat(path,'ir_use_hui\'),'ext','jpg'),...
        %struct('name','15','path',strcat(path,'ir_use_hui\'),'ext','jpg'),...
        %struct('name','16','path',strcat(path,'ir_use_hui\'),'ext','jpg'),...
        %struct('name','17','path',strcat(path,'ir_use_hui\'),'ext','jpg'),...
        
        
        
        %struct('name','1','path',strcat(path,'ir_thermal\'),'ext','jpg'),...
        %struct('name','RAD2','path',strcat(path,'ir_thermal\'),'ext','bmp'),...
        %struct('name','RAD3','path',strcat(path,'ir_thermal\'),'ext','bmp'),...
        %struct('name','RAD4','path',strcat(path,'ir_thermal\'),'ext','bmp'),...
        %struct('name','RAD5','path',strcat(path,'ir_thermal\'),'ext','bmp'),...
        %struct('name','RAD6','path',strcat(path,'ir_thermal\'),'ext','bmp'),...
        %struct('name','RAD7','path',strcat(path,'ir_thermal\'),'ext','bmp'),...
        %struct('name','RAD8','path',strcat(path,'ir_thermal\'),'ext','bmp'),...
        %struct('name','RAD9','path',strcat(path,'ir_thermal\'),'ext','bmp'),...
        %struct('name','RAD10','path',strcat(path,'ir_thermal\'),'ext','bmp'),...
        %struct('name','RAD11','path',strcat(path,'ir_thermal\'),'ext','bmp'),...
        %struct('name','RAD12','path',strcat(path,'ir_thermal\'),'ext','bmp'),...
        %struct('name','RAD13','path',strcat(path,'ir_thermal\'),'ext','bmp'),...
        %struct('name','RAD14','path',strcat(path,'ir_thermal\'),'ext','bmp'),...
        %struct('name','RAD15','path',strcat(path,'ir_thermal\'),'ext','bmp'),...
        %struct('name','RAD16','path',strcat(path,'ir_thermal\'),'ext','bmp'),...
        %struct('name','RAD17','path',strcat(path,'ir_thermal\'),'ext','bmp'),...
        %struct('name','RAD18','path',strcat(path,'ir_thermal\'),'ext','bmp'),...
        %struct('name','RAD19','path',strcat(path,'ir_thermal\'),'ext','bmp'),...
        %struct('name','RAD20','path',strcat(path,'ir_thermal\'),'ext','bmp'),...
        %struct('name','RAD21','path',strcat(path,'ir_thermal\'),'ext','bmp'),...
        %struct('name','RAD22','path',strcat(path,'ir_thermal\'),'ext','bmp'),...
        %struct('name','RAD23','path',strcat(path,'ir_thermal\'),'ext','bmp'),...
        %struct('name','RAD24','path',strcat(path,'ir_thermal\'),'ext','bmp'),...
        %struct('name','RAD25','path',strcat(path,'ir_thermal\'),'ext','bmp'),...
        %struct('name','RAD26','path',strcat(path,'ir_thermal\'),'ext','bmp'),...
        %struct('name','RAD27','path',strcat(path,'ir_thermal\'),'ext','bmp'),...
        %struct('name','RAD28','path',strcat(path,'ir_thermal\'),'ext','bmp'),...
        %struct('name','RAD29','path',strcat(path,'ir_thermal\'),'ext','bmp'),...
        
        %struct('name','RAD30','path',strcat(path,'ir_thermal\'),'ext','bmp'),...
        %struct('name','RAD31','path',strcat(path,'ir_thermal\'),'ext','bmp'),...
        %struct('name','RAD32','path',strcat(path,'ir_thermal\'),'ext','bmp'),...
        %struct('name','RAD33','path',strcat(path,'ir_thermal\'),'ext','bmp'),...
        %struct('name','RAD34','path',strcat(path,'ir_thermal\'),'ext','bmp'),...
        %struct('name','RAD35','path',strcat(path,'ir_thermal\'),'ext','bmp'),...
        %struct('name','RAD36','path',strcat(path,'ir_thermal\'),'ext','bmp'),...
        %struct('name','RAD37','path',strcat(path,'ir_thermal\'),'ext','bmp'),...
        %struct('name','RAD38','path',strcat(path,'ir_thermal\'),'ext','bmp'),...
        %struct('name','RAD39','path',strcat(path,'ir_thermal\'),'ext','bmp'),...
        %struct('name','RAD40','path',strcat(path,'ir_thermal\'),'ext','bmp'),...
        %struct('name','RAD41','path',strcat(path,'ir_thermal\'),'ext','bmp'),...
        %struct('name','RAD42','path',strcat(path,'ir_thermal\'),'ext','bmp'),...
        %struct('name','RAD43','path',strcat(path,'ir_thermal\'),'ext','bmp'),...
        %struct('name','RAD44','path',strcat(path,'ir_thermal\'),'ext','bmp'),...
        %struct('name','RAD45','path',strcat(path,'ir_thermal\'),'ext','bmp'),...
        %struct('name','RAD46','path',strcat(path,'ir_thermal\'),'ext','bmp'),...
        
        
       % 实验用的第一个数据集
        %{
        struct('name','1','path',strcat(path,'part321_ir\'),'ext','bmp'),...%part 3
        struct('name','2','path',strcat(path,'part321_ir\'),'ext','bmp'),...
        struct('name','3','path',strcat(path,'part321_ir\'),'ext','bmp'),...
        struct('name','4','path',strcat(path,'part321_ir\'),'ext','bmp'),...
        struct('name','5','path',strcat(path,'part321_ir\'),'ext','bmp'),...
        struct('name','6','path',strcat(path,'part321_ir\'),'ext','bmp'),...
        struct('name','7','path',strcat(path,'part321_ir\'),'ext','bmp'),...
        struct('name','8','path',strcat(path,'part321_ir\'),'ext','bmp'),...
        struct('name','9','path',strcat(path,'part321_ir\'),'ext','bmp'),...
        struct('name','10','path',strcat(path,'part321_ir\'),'ext','bmp'),...
        struct('name','11','path',strcat(path,'part321_ir\'),'ext','bmp'),...
        struct('name','12','path',strcat(path,'part321_ir\'),'ext','bmp'),...
        struct('name','13','path',strcat(path,'part321_ir\'),'ext','bmp'),...
        struct('name','14','path',strcat(path,'part321_ir\'),'ext','bmp'),...
        struct('name','15','path',strcat(path,'part321_ir\'),'ext','bmp'),...
        struct('name','16','path',strcat(path,'part321_ir\'),'ext','bmp'),...
        struct('name','17','path',strcat(path,'part321_ir\'),'ext','bmp'),...
        struct('name','18','path',strcat(path,'part321_ir\'),'ext','bmp'),...
        struct('name','19','path',strcat(path,'part321_ir\'),'ext','bmp'),...
        struct('name','20','path',strcat(path,'part321_ir\'),'ext','bmp'),...
        struct('name','21','path',strcat(path,'part321_ir\'),'ext','bmp'),...
        struct('name','22','path',strcat(path,'part321_ir\'),'ext','bmp'),...
        struct('name','23','path',strcat(path,'part321_ir\'),'ext','bmp'),...
        struct('name','24','path',strcat(path,'part321_ir\'),'ext','bmp'),...
        struct('name','25','path',strcat(path,'part321_ir\'),'ext','bmp'),...
        struct('name','26','path',strcat(path,'part321_ir\'),'ext','bmp'),...
        struct('name','27','path',strcat(path,'part321_ir\'),'ext','bmp'),...
        struct('name','28','path',strcat(path,'part321_ir\'),'ext','bmp'),...
        struct('name','29','path',strcat(path,'part321_ir\'),'ext','bmp'),...
        struct('name','30','path',strcat(path,'part321_ir\'),'ext','bmp'),...
        struct('name','31','path',strcat(path,'part321_ir\'),'ext','bmp'),...
        struct('name','32','path',strcat(path,'part321_ir\'),'ext','bmp'),...
        struct('name','33','path',strcat(path,'part321_ir\'),'ext','bmp'),...
        struct('name','34','path',strcat(path,'part321_ir\'),'ext','bmp'),...
        struct('name','35','path',strcat(path,'part321_ir\'),'ext','bmp'),...
        struct('name','36','path',strcat(path,'part321_ir\'),'ext','bmp'),...
        struct('name','37','path',strcat(path,'part321_ir\'),'ext','bmp'),...
        struct('name','38','path',strcat(path,'part321_ir\'),'ext','bmp'),...
        struct('name','39','path',strcat(path,'part321_ir\'),'ext','bmp'),...
        struct('name','40','path',strcat(path,'part321_ir\'),'ext','bmp'),...
        struct('name','41','path',strcat(path,'part321_ir\'),'ext','bmp'),...
        struct('name','42','path',strcat(path,'part321_ir\'),'ext','bmp'),...
        struct('name','43','path',strcat(path,'part321_ir\'),'ext','bmp'),...
        struct('name','44','path',strcat(path,'part321_ir\'),'ext','bmp'),...
        struct('name','45','path',strcat(path,'part321_ir\'),'ext','bmp'),...
        struct('name','46','path',strcat(path,'part321_ir\'),'ext','bmp'),...
        struct('name','47','path',strcat(path,'part321_ir\'),'ext','bmp'),...
        struct('name','48','path',strcat(path,'part321_ir\'),'ext','bmp'),...
        struct('name','49','path',strcat(path,'part321_ir\'),'ext','bmp'),...
        struct('name','50','path',strcat(path,'part321_ir\'),'ext','bmp'),...
        struct('name','51','path',strcat(path,'part321_ir\'),'ext','bmp'),...
        struct('name','52','path',strcat(path,'part321_ir\'),'ext','bmp'),...
        struct('name','53','path',strcat(path,'part321_ir\'),'ext','bmp'),...
        struct('name','54','path',strcat(path,'part321_ir\'),'ext','bmp'),...
        struct('name','55','path',strcat(path,'part321_ir\'),'ext','bmp'),...
        struct('name','56','path',strcat(path,'part321_ir\'),'ext','bmp'),...
        struct('name','57','path',strcat(path,'part321_ir\'),'ext','bmp'),...
        struct('name','58','path',strcat(path,'part321_ir\'),'ext','bmp'),...
        struct('name','59','path',strcat(path,'part321_ir\'),'ext','bmp'),...
        struct('name','60','path',strcat(path,'part321_ir\'),'ext','bmp'),...
        struct('name','61','path',strcat(path,'part321_ir\'),'ext','bmp'),...
        struct('name','62','path',strcat(path,'part321_ir\'),'ext','bmp'),...%part 2
        struct('name','63','path',strcat(path,'part321_ir\'),'ext','bmp'),...
        struct('name','64','path',strcat(path,'part321_ir\'),'ext','bmp'),...
        struct('name','65','path',strcat(path,'part321_ir\'),'ext','bmp'),...
        struct('name','66','path',strcat(path,'part321_ir\'),'ext','bmp'),...
        struct('name','67','path',strcat(path,'part321_ir\'),'ext','bmp'),...
        struct('name','68','path',strcat(path,'part321_ir\'),'ext','bmp'),...
        struct('name','69','path',strcat(path,'part321_ir\'),'ext','bmp'),...
        struct('name','70','path',strcat(path,'part321_ir\'),'ext','bmp'),...
        struct('name','71','path',strcat(path,'part321_ir\'),'ext','bmp'),...
        struct('name','72','path',strcat(path,'part321_ir\'),'ext','bmp'),...
        struct('name','73','path',strcat(path,'part321_ir\'),'ext','bmp'),...
        struct('name','74','path',strcat(path,'part321_ir\'),'ext','bmp'),...
        struct('name','75','path',strcat(path,'part321_ir\'),'ext','bmp'),...
        struct('name','76','path',strcat(path,'part321_ir\'),'ext','bmp'),...
        struct('name','77','path',strcat(path,'part321_ir\'),'ext','bmp'),...
        struct('name','78','path',strcat(path,'part321_ir\'),'ext','bmp'),...
        struct('name','79','path',strcat(path,'part321_ir\'),'ext','bmp'),...%part 1
        struct('name','80','path',strcat(path,'part321_ir\'),'ext','bmp'),...
        struct('name','81','path',strcat(path,'part321_ir\'),'ext','bmp'),...
        struct('name','82','path',strcat(path,'part321_ir\'),'ext','bmp'),...
        struct('name','83','path',strcat(path,'part321_ir\'),'ext','bmp'),...
        struct('name','84','path',strcat(path,'part321_ir\'),'ext','bmp'),...
        struct('name','85','path',strcat(path,'part321_ir\'),'ext','bmp'),...
        struct('name','86','path',strcat(path,'part321_ir\'),'ext','bmp'),...
        struct('name','87','path',strcat(path,'part321_ir\'),'ext','bmp'),...
        struct('name','88','path',strcat(path,'part321_ir\'),'ext','bmp'),...
        struct('name','89','path',strcat(path,'part321_ir\'),'ext','bmp'),...
        struct('name','90','path',strcat(path,'part321_ir\'),'ext','bmp'),...
        struct('name','91','path',strcat(path,'part321_ir\'),'ext','bmp'),...
        struct('name','92','path',strcat(path,'part321_ir\'),'ext','bmp'),...
        struct('name','93','path',strcat(path,'part321_ir\'),'ext','bmp'),...
        struct('name','94','path',strcat(path,'part321_ir\'),'ext','bmp'),...
        struct('name','95','path',strcat(path,'part321_ir\'),'ext','bmp'),...
        struct('name','96','path',strcat(path,'part321_ir\'),'ext','bmp'),...
        struct('name','97','path',strcat(path,'part321_ir\'),'ext','bmp'),...
        struct('name','98','path',strcat(path,'part321_ir\'),'ext','bmp'),...
        struct('name','99','path',strcat(path,'part321_ir\'),'ext','bmp'),...
        struct('name','100','path',strcat(path,'part321_ir\'),'ext','bmp'),...
        struct('name','101','path',strcat(path,'part321_ir\'),'ext','bmp'),...
        struct('name','102','path',strcat(path,'part321_ir\'),'ext','bmp'),...
        struct('name','103','path',strcat(path,'part321_ir\'),'ext','bmp'),...
        struct('name','104','path',strcat(path,'part321_ir\'),'ext','bmp'),...
        struct('name','105','path',strcat(path,'part321_ir\'),'ext','bmp'),...
        struct('name','106','path',strcat(path,'part321_ir\'),'ext','bmp'),...
        %}
        
        
        struct('name','1','path',strcat(path,'ir_bmp_hui\'),'ext','bmp'),...%part 3
        struct('name','2','path',strcat(path,'ir_bmp_hui\'),'ext','bmp'),...
        struct('name','3','path',strcat(path,'ir_bmp_hui\'),'ext','bmp'),...
        struct('name','4','path',strcat(path,'ir_bmp_hui\'),'ext','bmp'),...
        struct('name','5','path',strcat(path,'ir_bmp_hui\'),'ext','bmp'),...
        struct('name','6','path',strcat(path,'ir_bmp_hui\'),'ext','bmp'),...
        struct('name','7','path',strcat(path,'ir_bmp_hui\'),'ext','bmp'),...
        struct('name','8','path',strcat(path,'ir_bmp_hui\'),'ext','bmp'),...
        struct('name','9','path',strcat(path,'ir_bmp_hui\'),'ext','bmp'),...
        struct('name','10','path',strcat(path,'ir_bmp_hui\'),'ext','bmp'),...
        struct('name','11','path',strcat(path,'ir_bmp_hui\'),'ext','bmp'),...
        struct('name','12','path',strcat(path,'ir_bmp_hui\'),'ext','bmp'),...
        struct('name','13','path',strcat(path,'ir_bmp_hui\'),'ext','bmp'),...
        struct('name','14','path',strcat(path,'ir_bmp_hui\'),'ext','bmp'),...
        struct('name','15','path',strcat(path,'ir_bmp_hui\'),'ext','bmp'),...
        struct('name','16','path',strcat(path,'ir_bmp_hui\'),'ext','bmp'),...
        struct('name','17','path',strcat(path,'ir_bmp_hui\'),'ext','bmp'),...
        struct('name','18','path',strcat(path,'ir_bmp_hui\'),'ext','bmp'),...
        struct('name','19','path',strcat(path,'ir_bmp_hui\'),'ext','bmp'),...
        struct('name','20','path',strcat(path,'ir_bmp_hui\'),'ext','bmp'),...
        struct('name','21','path',strcat(path,'ir_bmp_hui\'),'ext','bmp'),...
        struct('name','22','path',strcat(path,'ir_bmp_hui\'),'ext','bmp'),...
        struct('name','23','path',strcat(path,'ir_bmp_hui\'),'ext','bmp'),...
        struct('name','24','path',strcat(path,'ir_bmp_hui\'),'ext','bmp'),...
        struct('name','25','path',strcat(path,'ir_bmp_hui\'),'ext','bmp'),...
        struct('name','26','path',strcat(path,'ir_bmp_hui\'),'ext','bmp'),...
        struct('name','27','path',strcat(path,'ir_bmp_hui\'),'ext','bmp'),...
        struct('name','28','path',strcat(path,'ir_bmp_hui\'),'ext','bmp'),...
        struct('name','29','path',strcat(path,'ir_bmp_hui\'),'ext','bmp'),...
        struct('name','30','path',strcat(path,'ir_bmp_hui\'),'ext','bmp'),...
        struct('name','31','path',strcat(path,'ir_bmp_hui\'),'ext','bmp'),...
        struct('name','32','path',strcat(path,'ir_bmp_hui\'),'ext','bmp'),...
        struct('name','33','path',strcat(path,'ir_bmp_hui\'),'ext','bmp'),...
        struct('name','34','path',strcat(path,'ir_bmp_hui\'),'ext','bmp'),...
        struct('name','35','path',strcat(path,'ir_bmp_hui\'),'ext','bmp'),...
        struct('name','36','path',strcat(path,'ir_bmp_hui\'),'ext','bmp'),...
        struct('name','37','path',strcat(path,'ir_bmp_hui\'),'ext','bmp'),...
        struct('name','38','path',strcat(path,'ir_bmp_hui\'),'ext','bmp'),...
        struct('name','39','path',strcat(path,'ir_bmp_hui\'),'ext','bmp'),...
        struct('name','40','path',strcat(path,'ir_bmp_hui\'),'ext','bmp'),...
        struct('name','41','path',strcat(path,'ir_bmp_hui\'),'ext','bmp'),...
        struct('name','42','path',strcat(path,'ir_bmp_hui\'),'ext','bmp'),...
 
        };
        
             
    elseif a == 2
        
    
        img_IR = {

        struct('name','1','path',strcat(path,'ir_512_384\'),'ext','jpg'),...
        struct('name','2','path',strcat(path,'ir_512_384\'),'ext','jpg'),...
        struct('name','3','path',strcat(path,'ir_512_384\'),'ext','jpg'),...
        struct('name','4','path',strcat(path,'ir_512_384\'),'ext','jpg'),...
        struct('name','5','path',strcat(path,'ir_512_384\'),'ext','jpg'),...
        struct('name','6','path',strcat(path,'ir_512_384\'),'ext','jpg'),...
        struct('name','7','path',strcat(path,'ir_512_384\'),'ext','jpg'),...
        struct('name','8','path',strcat(path,'ir_512_384\'),'ext','jpg'),...
        struct('name','9','path',strcat(path,'ir_512_384\'),'ext','jpg'),...
        struct('name','10','path',strcat(path,'ir_512_384\'),'ext','jpg'),...
        struct('name','11','path',strcat(path,'ir_512_384\'),'ext','jpg'),...
        struct('name','12','path',strcat(path,'ir_512_384\'),'ext','jpg'),...
        struct('name','13','path',strcat(path,'ir_512_384\'),'ext','jpg'),...
        struct('name','14','path',strcat(path,'ir_512_384\'),'ext','jpg'),...
        struct('name','15','path',strcat(path,'ir_512_384\'),'ext','jpg'),...
        struct('name','16','path',strcat(path,'ir_512_384\'),'ext','jpg'),...
        struct('name','17','path',strcat(path,'ir_512_384\'),'ext','jpg'),...
        struct('name','18','path',strcat(path,'ir_512_384\'),'ext','jpg'),...
        struct('name','19','path',strcat(path,'ir_512_384\'),'ext','jpg'),...
        struct('name','20','path',strcat(path,'ir_512_384\'),'ext','jpg'),...
        struct('name','21','path',strcat(path,'ir_512_384\'),'ext','jpg'),...
        struct('name','22','path',strcat(path,'ir_512_384\'),'ext','jpg'),...
        struct('name','23','path',strcat(path,'ir_512_384\'),'ext','jpg'),...
        struct('name','24','path',strcat(path,'ir_512_384\'),'ext','jpg'),...
        struct('name','25','path',strcat(path,'ir_512_384\'),'ext','jpg'),...
        
        struct('name','26','path',strcat(path,'ir_512_384\'),'ext','jpg'),...

        
        };
    else
        error('Invalid value of a ir!');
        end

imgs=[img_IR];