% This is used to set the path to visible images
%?????????????????????????????????
% Please change the path in line 16 to your own path before running
%?????????????????????16???????????????????????????????????????
% Author:Xingchen Zhang, Ping Ye, Gang Xiao
% Contact: xingchen.zhang@imperial.ac.uk
%
% If you use this code, please site the following paper:
%
% X. Zhang, P. Ye, G. Xiao. VIFB:A Visible and Infrared Benchmark. In
% Proceedings of the IEEE/CVF Conference on Computer Vision and Pattern
% Recognition Workshops, 2020.

function imgs=configImgsVI

    path = 'C:\Users\Administrator\Desktop\20230225VIF\VIFB1\input\roadscene\';

    
    a = 1
    
    if a == 2
    
        img_VI = {

        struct('name','1','path',strcat(path,'Visible1_512_384_hui\'),'ext','jpg'),...
        struct('name','2','path',strcat(path,'Visible1_512_384_hui\'),'ext','jpg'),...
        struct('name','3','path',strcat(path,'Visible1_512_384_hui\'),'ext','jpg'),...
        struct('name','4','path',strcat(path,'Visible1_512_384_hui\'),'ext','jpg'),...
        struct('name','5','path',strcat(path,'Visible1_512_384_hui\'),'ext','jpg'),...
        struct('name','6','path',strcat(path,'Visible1_512_384_hui\'),'ext','jpg'),...
        struct('name','7','path',strcat(path,'Visible1_512_384_hui\'),'ext','jpg'),...
        struct('name','8','path',strcat(path,'Visible1_512_384_hui\'),'ext','jpg'),...
        struct('name','9','path',strcat(path,'Visible1_512_384_hui\'),'ext','jpg'),...
        struct('name','10','path',strcat(path,'Visible1_512_384_hui\'),'ext','jpg'),...
        struct('name','11','path',strcat(path,'Visible1_512_384_hui\'),'ext','jpg'),...
        struct('name','12','path',strcat(path,'Visible1_512_384_hui\'),'ext','jpg'),...
        struct('name','13','path',strcat(path,'Visible1_512_384_hui\'),'ext','jpg'),...
        struct('name','14','path',strcat(path,'Visible1_512_384_hui\'),'ext','jpg'),...
        struct('name','15','path',strcat(path,'Visible1_512_384_hui\'),'ext','jpg'),...
        struct('name','16','path',strcat(path,'Visible1_512_384_hui\'),'ext','jpg'),...
        struct('name','17','path',strcat(path,'Visible1_512_384_hui\'),'ext','jpg'),...
        struct('name','18','path',strcat(path,'Visible1_512_384_hui\'),'ext','jpg'),...
        struct('name','19','path',strcat(path,'Visible1_512_384_hui\'),'ext','jpg'),...
        struct('name','20','path',strcat(path,'Visible1_512_384_hui\'),'ext','jpg'),...
        struct('name','21','path',strcat(path,'Visible1_512_384_hui\'),'ext','jpg'),...
        struct('name','22','path',strcat(path,'Visible1_512_384_hui\'),'ext','jpg'),...
        struct('name','23','path',strcat(path,'Visible1_512_384_hui\'),'ext','jpg'),...
        struct('name','24','path',strcat(path,'Visible1_512_384_hui\'),'ext','jpg'),...
        struct('name','25','path',strcat(path,'Visible1_512_384_hui\'),'ext','jpg'),...
        
        struct('name','26','path',strcat(path,'Visible1_512_384_hui\'),'ext','jpg'),...

        
        
        };
    
    elseif a == 1

        img_VI = {
        %struct('name','A1','path',strcat(path,'Visible1\'),'ext','jpg'),...
        %struct('name','A2','path',strcat(path,'Visible1\'),'ext','jpg'),...
        %struct('name','A3','path',strcat(path,'Visible1\'),'ext','jpg'),...
        %struct('name','A4','path',strcat(path,'Visible1\'),'ext','jpg'),...
        %struct('name','A5','path',strcat(path,'Visible1\'),'ext','jpg'),...
        %struct('name','A6','path',strcat(path,'Visible1\'),'ext','jpg'),...
        %struct('name','A7','path',strcat(path,'Visible1\'),'ext','jpg'),...
        %struct('name','A8','path',strcat(path,'Visible1\'),'ext','jpg'),...
        %struct('name','A9','path',strcat(path,'Visible1\'),'ext','jpg'),...
        %struct('name','A10','path',strcat(path,'Visible1\'),'ext','jpg'),...
        %struct('name','A11','path',strcat(path,'Visible1\'),'ext','jpg'),...
        %struct('name','A12','path',strcat(path,'Visible1\'),'ext','jpg'),...
        %struct('name','A13','path',strcat(path,'Visible1\'),'ext','jpg'),...
        %struct('name','A14','path',strcat(path,'Visible1\'),'ext','jpg'),...
        %struct('name','A15','path',strcat(path,'Visible1\'),'ext','jpg'),...
        %struct('name','A16','path',strcat(path,'Visible1\'),'ext','jpg'),...
        %struct('name','A17','path',strcat(path,'Visible1\'),'ext','jpg'),...
        %struct('name','A18','path',strcat(path,'Visible1\'),'ext','jpg'),...
        %struct('name','A19','path',strcat(path,'Visible1\'),'ext','jpg'),...
        %struct('name','A20','path',strcat(path,'Visible1\'),'ext','jpg'),...
        %struct('name','A21','path',strcat(path,'Visible1\'),'ext','jpg'),...
        %struct('name','A22','path',strcat(path,'Visible1\'),'ext','jpg'),...
        %struct('name','A23','path',strcat(path,'Visible1\'),'ext','jpg'),...
        %struct('name','A24','path',strcat(path,'Visible1\'),'ext','jpg'),...
        %struct('name','A25','path',strcat(path,'Visible1\'),'ext','jpg'),...
            
        %struct('name','1','path',strcat(path,'rgb_use\'),'ext','jpg'),...
        %struct('name','2','path',strcat(path,'rgb_use\'),'ext','jpg'),...
        %struct('name','3','path',strcat(path,'rgb_use\'),'ext','jpg'),...
        %struct('name','4','path',strcat(path,'rgb_use\'),'ext','jpg'),...
        %struct('name','5','path',strcat(path,'rgb_use\'),'ext','jpg'),...
        %struct('name','6','path',strcat(path,'rgb_use\'),'ext','jpg'),...
        %struct('name','7','path',strcat(path,'rgb_use\'),'ext','jpg'),...
        %struct('name','8','path',strcat(path,'rgb_use\'),'ext','jpg'),...
        %struct('name','9','path',strcat(path,'rgb_use\'),'ext','jpg'),...
        %struct('name','10','path',strcat(path,'rgb_use\'),'ext','jpg'),...
        %struct('name','11','path',strcat(path,'rgb_use\'),'ext','jpg'),...
        %struct('name','12','path',strcat(path,'rgb_use\'),'ext','jpg'),...
        %struct('name','13','path',strcat(path,'rgb_use\'),'ext','jpg'),...
        %struct('name','14','path',strcat(path,'rgb_use\'),'ext','jpg'),...
        %struct('name','15','path',strcat(path,'rgb_use\'),'ext','jpg'),...
        %struct('name','16','path',strcat(path,'rgb_use\'),'ext','jpg'),...
        %struct('name','17','path',strcat(path,'rgb_use\'),'ext','jpg'),...
        
        
        
        %struct('name','1','path',strcat(path,'rgb_dhv_hui\'),'ext','bmp'),...
        %struct('name','DHV2','path',strcat(path,'rgb_dhv_hui\'),'ext','bmp'),...
        %struct('name','DHV3','path',strcat(path,'rgb_dhv_hui\'),'ext','bmp'),...
        %struct('name','DHV4','path',strcat(path,'rgb_dhv_hui\'),'ext','bmp'),...
        %struct('name','DHV5','path',strcat(path,'rgb_dhv_hui\'),'ext','bmp'),...
        %struct('name','DHV6','path',strcat(path,'rgb_dhv_hui\'),'ext','bmp'),...
        %struct('name','DHV7','path',strcat(path,'rgb_dhv_hui\'),'ext','bmp'),...
        %struct('name','DHV8','path',strcat(path,'rgb_dhv_hui\'),'ext','bmp'),...
        %struct('name','DHV9','path',strcat(path,'rgb_dhv_hui\'),'ext','bmp'),...
        %struct('name','DHV10','path',strcat(path,'rgb_dhv_hui\'),'ext','bmp'),...
        %struct('name','DHV11','path',strcat(path,'rgb_dhv_hui\'),'ext','bmp'),...
        %struct('name','DHV12','path',strcat(path,'rgb_dhv_hui\'),'ext','bmp'),...
        %struct('name','DHV13','path',strcat(path,'rgb_dhv_hui\'),'ext','bmp'),...
        %struct('name','DHV14','path',strcat(path,'rgb_dhv_hui\'),'ext','bmp'),...
        %struct('name','DHV15','path',strcat(path,'rgb_dhv_hui\'),'ext','bmp'),...
        %struct('name','DHV16','path',strcat(path,'rgb_dhv_hui\'),'ext','bmp'),...
        %struct('name','DHV17','path',strcat(path,'rgb_dhv_hui\'),'ext','bmp'),...
        %struct('name','DHV18','path',strcat(path,'rgb_dhv_hui\'),'ext','bmp'),...
        %struct('name','DHV19','path',strcat(path,'rgb_dhv_hui\'),'ext','bmp'),...
        %struct('name','DHV20','path',strcat(path,'rgb_dhv_hui\'),'ext','bmp'),...
        %struct('name','DHV21','path',strcat(path,'rgb_dhv_hui\'),'ext','bmp'),...
        %struct('name','DHV22','path',strcat(path,'rgb_dhv_hui\'),'ext','bmp'),...
        %struct('name','DHV23','path',strcat(path,'rgb_dhv_hui\'),'ext','bmp'),...
        %struct('name','DHV24','path',strcat(path,'rgb_dhv_hui\'),'ext','bmp'),...
        %struct('name','DHV25','path',strcat(path,'rgb_dhv_hui\'),'ext','bmp'),...
        %struct('name','DHV26','path',strcat(path,'rgb_dhv_hui\'),'ext','bmp'),...
        %struct('name','DHV27','path',strcat(path,'rgb_dhv_hui\'),'ext','bmp'),...
        %struct('name','DHV28','path',strcat(path,'rgb_dhv_hui\'),'ext','bmp'),...
        %struct('name','DHV29','path',strcat(path,'rgb_dhv_hui\'),'ext','bmp'),...
               
        %struct('name','DHV30','path',strcat(path,'rgb_dhv_hui\'),'ext','bmp'),...
        %struct('name','DHV31','path',strcat(path,'rgb_dhv_hui\'),'ext','bmp'),...
        %struct('name','DHV32','path',strcat(path,'rgb_dhv_hui\'),'ext','bmp'),...
        %struct('name','DHV33','path',strcat(path,'rgb_dhv_hui\'),'ext','bmp'),...
        %struct('name','DHV34','path',strcat(path,'rgb_dhv_hui\'),'ext','bmp'),...
        %struct('name','DHV35','path',strcat(path,'rgb_dhv_hui\'),'ext','bmp'),...
       % struct('name','DHV36','path',strcat(path,'rgb_dhv_hui\'),'ext','bmp'),...
        %struct('name','DHV37','path',strcat(path,'rgb_dhv_hui\'),'ext','bmp'),...
        %struct('name','DHV38','path',strcat(path,'rgb_dhv_hui\'),'ext','bmp'),...
        %struct('name','DHV39','path',strcat(path,'rgb_dhv_hui\'),'ext','bmp'),...
        %struct('name','DHV40','path',strcat(path,'rgb_dhv_hui\'),'ext','bmp'),...
        %struct('name','DHV41','path',strcat(path,'rgb_dhv_hui\'),'ext','bmp'),...
        %struct('name','DHV42','path',strcat(path,'rgb_dhv_hui\'),'ext','bmp'),...
        %struct('name','DHV43','path',strcat(path,'rgb_dhv_hui\'),'ext','bmp'),...
        %struct('name','DHV44','path',strcat(path,'rgb_dhv_hui\'),'ext','bmp'),...
        %struct('name','DHV45','path',strcat(path,'rgb_dhv_hui\'),'ext','bmp'),...
        %struct('name','DHV46','path',strcat(path,'rgb_dhv_hui\'),'ext','bmp'),...
         
        
        % 实验用的第一个数据集
       %{ 
        struct('name','1','path',strcat(path,'part321_rgb\'),'ext','bmp'),...%part 2
        struct('name','2','path',strcat(path,'part321_rgb\'),'ext','bmp'),...
        struct('name','3','path',strcat(path,'part321_rgb\'),'ext','bmp'),...
        struct('name','4','path',strcat(path,'part321_rgb\'),'ext','bmp'),...
        struct('name','5','path',strcat(path,'part321_rgb\'),'ext','bmp'),...
        struct('name','6','path',strcat(path,'part321_rgb\'),'ext','bmp'),...
        struct('name','7','path',strcat(path,'part321_rgb\'),'ext','bmp'),...
        struct('name','8','path',strcat(path,'part321_rgb\'),'ext','bmp'),...
        struct('name','9','path',strcat(path,'part321_rgb\'),'ext','bmp'),...
        struct('name','10','path',strcat(path,'part321_rgb\'),'ext','bmp'),...
        struct('name','11','path',strcat(path,'part321_rgb\'),'ext','bmp'),...
        struct('name','12','path',strcat(path,'part321_rgb\'),'ext','bmp'),...
        struct('name','13','path',strcat(path,'part321_rgb\'),'ext','bmp'),...
        struct('name','14','path',strcat(path,'part321_rgb\'),'ext','bmp'),...
        struct('name','15','path',strcat(path,'part321_rgb\'),'ext','bmp'),...
        struct('name','16','path',strcat(path,'part321_rgb\'),'ext','bmp'),...
        struct('name','17','path',strcat(path,'part321_rgb\'),'ext','bmp'),...
        struct('name','18','path',strcat(path,'part321_rgb\'),'ext','bmp'),...
        struct('name','19','path',strcat(path,'part321_rgb\'),'ext','bmp'),...
        struct('name','20','path',strcat(path,'part321_rgb\'),'ext','bmp'),...
        struct('name','21','path',strcat(path,'part321_rgb\'),'ext','bmp'),...
        struct('name','22','path',strcat(path,'part321_rgb\'),'ext','bmp'),...
        struct('name','23','path',strcat(path,'part321_rgb\'),'ext','bmp'),...
        struct('name','24','path',strcat(path,'part321_rgb\'),'ext','bmp'),...
        struct('name','25','path',strcat(path,'part321_rgb\'),'ext','bmp'),...
        struct('name','26','path',strcat(path,'part321_rgb\'),'ext','bmp'),...
        struct('name','27','path',strcat(path,'part321_rgb\'),'ext','bmp'),...
        struct('name','28','path',strcat(path,'part321_rgb\'),'ext','bmp'),...
        struct('name','29','path',strcat(path,'part321_rgb\'),'ext','bmp'),...
        struct('name','30','path',strcat(path,'part321_rgb\'),'ext','bmp'),...
        struct('name','31','path',strcat(path,'part321_rgb\'),'ext','bmp'),...
        struct('name','32','path',strcat(path,'part321_rgb\'),'ext','bmp'),...
        struct('name','33','path',strcat(path,'part321_rgb\'),'ext','bmp'),...
        struct('name','34','path',strcat(path,'part321_rgb\'),'ext','bmp'),...
        struct('name','35','path',strcat(path,'part321_rgb\'),'ext','bmp'),...
        struct('name','36','path',strcat(path,'part321_rgb\'),'ext','bmp'),...
        struct('name','37','path',strcat(path,'part321_rgb\'),'ext','bmp'),...
        struct('name','38','path',strcat(path,'part321_rgb\'),'ext','bmp'),...
        struct('name','39','path',strcat(path,'part321_rgb\'),'ext','bmp'),...
        struct('name','40','path',strcat(path,'part321_rgb\'),'ext','bmp'),...
        struct('name','41','path',strcat(path,'part321_rgb\'),'ext','bmp'),...
        struct('name','42','path',strcat(path,'part321_rgb\'),'ext','bmp'),...
        struct('name','43','path',strcat(path,'part321_rgb\'),'ext','bmp'),...
        struct('name','44','path',strcat(path,'part321_rgb\'),'ext','bmp'),...
        struct('name','45','path',strcat(path,'part321_rgb\'),'ext','bmp'),...
        struct('name','46','path',strcat(path,'part321_rgb\'),'ext','bmp'),...
        struct('name','47','path',strcat(path,'part321_rgb\'),'ext','bmp'),...
        struct('name','48','path',strcat(path,'part321_rgb\'),'ext','bmp'),...
        struct('name','49','path',strcat(path,'part321_rgb\'),'ext','bmp'),...
        struct('name','50','path',strcat(path,'part321_rgb\'),'ext','bmp'),...
        struct('name','51','path',strcat(path,'part321_rgb\'),'ext','bmp'),...
        struct('name','52','path',strcat(path,'part321_rgb\'),'ext','bmp'),...
        struct('name','53','path',strcat(path,'part321_rgb\'),'ext','bmp'),...
        struct('name','54','path',strcat(path,'part321_rgb\'),'ext','bmp'),...
        struct('name','55','path',strcat(path,'part321_rgb\'),'ext','bmp'),...
        struct('name','56','path',strcat(path,'part321_rgb\'),'ext','bmp'),...
        struct('name','57','path',strcat(path,'part321_rgb\'),'ext','bmp'),...
        struct('name','58','path',strcat(path,'part321_rgb\'),'ext','bmp'),...
        struct('name','59','path',strcat(path,'part321_rgb\'),'ext','bmp'),...
        struct('name','60','path',strcat(path,'part321_rgb\'),'ext','bmp'),...
        struct('name','61','path',strcat(path,'part321_rgb\'),'ext','bmp'),...     
        struct('name','62','path',strcat(path,'part321_rgb\'),'ext','bmp'),...%part 2
        struct('name','63','path',strcat(path,'part321_rgb\'),'ext','bmp'),...
        struct('name','64','path',strcat(path,'part321_rgb\'),'ext','bmp'),...
        struct('name','65','path',strcat(path,'part321_rgb\'),'ext','bmp'),...
        struct('name','66','path',strcat(path,'part321_rgb\'),'ext','bmp'),...
        struct('name','67','path',strcat(path,'part321_rgb\'),'ext','bmp'),...
        struct('name','68','path',strcat(path,'part321_rgb\'),'ext','bmp'),...
        struct('name','69','path',strcat(path,'part321_rgb\'),'ext','bmp'),...
        struct('name','70','path',strcat(path,'part321_rgb\'),'ext','bmp'),...
        struct('name','71','path',strcat(path,'part321_rgb\'),'ext','bmp'),...
        struct('name','72','path',strcat(path,'part321_rgb\'),'ext','bmp'),...
        struct('name','73','path',strcat(path,'part321_rgb\'),'ext','bmp'),...
        struct('name','74','path',strcat(path,'part321_rgb\'),'ext','bmp'),...
        struct('name','75','path',strcat(path,'part321_rgb\'),'ext','bmp'),...
        struct('name','76','path',strcat(path,'part321_rgb\'),'ext','bmp'),...
        struct('name','77','path',strcat(path,'part321_rgb\'),'ext','bmp'),...
        struct('name','78','path',strcat(path,'part321_rgb\'),'ext','bmp'),...
        struct('name','79','path',strcat(path,'part321_rgb\'),'ext','bmp'),...%part 1
        struct('name','80','path',strcat(path,'part321_rgb\'),'ext','bmp'),...
        struct('name','81','path',strcat(path,'part321_rgb\'),'ext','bmp'),...
        struct('name','82','path',strcat(path,'part321_rgb\'),'ext','bmp'),...
        struct('name','83','path',strcat(path,'part321_rgb\'),'ext','bmp'),...
        struct('name','84','path',strcat(path,'part321_rgb\'),'ext','bmp'),...
        struct('name','85','path',strcat(path,'part321_rgb\'),'ext','bmp'),...
        struct('name','86','path',strcat(path,'part321_rgb\'),'ext','bmp'),...
        struct('name','87','path',strcat(path,'part321_rgb\'),'ext','bmp'),...
        struct('name','88','path',strcat(path,'part321_rgb\'),'ext','bmp'),...
        struct('name','89','path',strcat(path,'part321_rgb\'),'ext','bmp'),...
        struct('name','90','path',strcat(path,'part321_rgb\'),'ext','bmp'),...
        struct('name','91','path',strcat(path,'part321_rgb\'),'ext','bmp'),...
        struct('name','92','path',strcat(path,'part321_rgb\'),'ext','bmp'),...
        struct('name','93','path',strcat(path,'part321_rgb\'),'ext','bmp'),...
        struct('name','94','path',strcat(path,'part321_rgb\'),'ext','bmp'),...
        struct('name','95','path',strcat(path,'part321_rgb\'),'ext','bmp'),...
        struct('name','96','path',strcat(path,'part321_rgb\'),'ext','bmp'),...
        struct('name','97','path',strcat(path,'part321_rgb\'),'ext','bmp'),...
        struct('name','98','path',strcat(path,'part321_rgb\'),'ext','bmp'),...
        struct('name','99','path',strcat(path,'part321_rgb\'),'ext','bmp'),...
        struct('name','100','path',strcat(path,'part321_rgb\'),'ext','bmp'),...
        struct('name','101','path',strcat(path,'part321_rgb\'),'ext','bmp'),...
        struct('name','102','path',strcat(path,'part321_rgb\'),'ext','bmp'),...
        struct('name','103','path',strcat(path,'part321_rgb\'),'ext','bmp'),...
        struct('name','104','path',strcat(path,'part321_rgb\'),'ext','bmp'),...
        struct('name','105','path',strcat(path,'part321_rgb\'),'ext','bmp'),...
        struct('name','106','path',strcat(path,'part321_rgb\'),'ext','bmp'),...
        %}
        
        
        % 这是用的第二个数据集
        struct('name','1','path',strcat(path,'vi_bmp_hui\'),'ext','bmp'),...
        struct('name','2','path',strcat(path,'vi_bmp_hui\'),'ext','bmp'),...
        struct('name','3','path',strcat(path,'vi_bmp_hui\'),'ext','bmp'),...
        struct('name','4','path',strcat(path,'vi_bmp_hui\'),'ext','bmp'),...
        struct('name','5','path',strcat(path,'vi_bmp_hui\'),'ext','bmp'),...
        struct('name','6','path',strcat(path,'vi_bmp_hui\'),'ext','bmp'),...
        struct('name','7','path',strcat(path,'vi_bmp_hui\'),'ext','bmp'),...
        struct('name','8','path',strcat(path,'vi_bmp_hui\'),'ext','bmp'),...
        struct('name','9','path',strcat(path,'vi_bmp_hui\'),'ext','bmp'),...
        struct('name','10','path',strcat(path,'vi_bmp_hui\'),'ext','bmp'),...
        struct('name','11','path',strcat(path,'vi_bmp_hui\'),'ext','bmp'),...
        struct('name','12','path',strcat(path,'vi_bmp_hui\'),'ext','bmp'),...
        struct('name','13','path',strcat(path,'vi_bmp_hui\'),'ext','bmp'),...
        struct('name','14','path',strcat(path,'vi_bmp_hui\'),'ext','bmp'),...
        struct('name','15','path',strcat(path,'vi_bmp_hui\'),'ext','bmp'),...
        struct('name','16','path',strcat(path,'vi_bmp_hui\'),'ext','bmp'),...
        struct('name','17','path',strcat(path,'vi_bmp_hui\'),'ext','bmp'),...
        struct('name','18','path',strcat(path,'vi_bmp_hui\'),'ext','bmp'),...
        struct('name','19','path',strcat(path,'vi_bmp_hui\'),'ext','bmp'),...
        struct('name','20','path',strcat(path,'vi_bmp_hui\'),'ext','bmp'),...
        struct('name','21','path',strcat(path,'vi_bmp_hui\'),'ext','bmp'),...
        struct('name','22','path',strcat(path,'vi_bmp_hui\'),'ext','bmp'),...
        struct('name','23','path',strcat(path,'vi_bmp_hui\'),'ext','bmp'),...
        struct('name','24','path',strcat(path,'vi_bmp_hui\'),'ext','bmp'),...
        struct('name','25','path',strcat(path,'vi_bmp_hui\'),'ext','bmp'),...
        struct('name','26','path',strcat(path,'vi_bmp_hui\'),'ext','bmp'),...
        struct('name','27','path',strcat(path,'vi_bmp_hui\'),'ext','bmp'),...
        struct('name','28','path',strcat(path,'vi_bmp_hui\'),'ext','bmp'),...
        struct('name','29','path',strcat(path,'vi_bmp_hui\'),'ext','bmp'),...
        struct('name','30','path',strcat(path,'vi_bmp_hui\'),'ext','bmp'),...
        struct('name','31','path',strcat(path,'vi_bmp_hui\'),'ext','bmp'),...
        struct('name','32','path',strcat(path,'vi_bmp_hui\'),'ext','bmp'),...
        struct('name','33','path',strcat(path,'vi_bmp_hui\'),'ext','bmp'),...
        struct('name','34','path',strcat(path,'vi_bmp_hui\'),'ext','bmp'),...
        struct('name','35','path',strcat(path,'vi_bmp_hui\'),'ext','bmp'),...
        struct('name','36','path',strcat(path,'vi_bmp_hui\'),'ext','bmp'),...
        struct('name','37','path',strcat(path,'vi_bmp_hui\'),'ext','bmp'),...
        struct('name','38','path',strcat(path,'vi_bmp_hui\'),'ext','bmp'),...
        struct('name','39','path',strcat(path,'vi_bmp_hui\'),'ext','bmp'),...
        struct('name','40','path',strcat(path,'vi_bmp_hui\'),'ext','bmp'),...
        struct('name','41','path',strcat(path,'vi_bmp_hui\'),'ext','bmp'),...
        struct('name','42','path',strcat(path,'vi_bmp_hui\'),'ext','bmp'),...
        
        
        
        };
    
    else
        error('Invalid value of a vi!');
        end
    

imgs=[img_VI];